### ISSUE TITLE
Anmelde-/Abmeldebutton

### ISSUE THREAD

**Issue by MSHY** [sventhiel/IngolStadtNatur#3]
Die grüne Menüleiste soll oben rechts einen Anmelde-/Abmeldebutton bekommen, der möglichst schlicht gestaltet ist (Beipielskizze): 
![img_4145](https://user-images.githubusercontent.com/29917852/28112999-40be6ec4-66fb-11e7-8eeb-9a8c8b0090cc.jpg)

(Daneben sichtbar ist das geplante Drop-Down-Menü, über das der User die interaktive Karte sowie die Galerie erreichen kann. Wird als Extra-Punkt aufgeführt werden.)

**Comment by sventhiel-zz** [comment]
SignIn
![image](https://user-images.githubusercontent.com/11521044/29619749-2710e7d0-881c-11e7-8763-e0b03ae4e84e.png)


SignOut
![image](https://user-images.githubusercontent.com/11521044/29619637-d8508fd8-881b-11e7-9311-8f5428bcbd8f.png)


Maybe it is worth to add some short text if the user is authenticated - "Hello X". But it could be an issue on small devices (e.g. smartphones). Because there is already the app name "IngolStadtNatur" on the left side.

Yet, the menu is not implemented because of missing functionalities.
